spring.application.name=backSpotic

spotify.client-id=c0035f43927d44e58ca577574040b42a
spotify.client-secret=32a4ac3b5ef3442d846a2bbe17258032
spotify.redirect-uri=https://127.0.0.1:8443/api/auth/callback
server.port=8443
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password
server.ssl.key-alias=tomcat

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true

logging.level.org.springframework.security=DEBUG


spring.datasource.url=jdbc:h2:mem:mi-proyecto-db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console